#!/usr/bin/env node
// Generates extension/background.js and bookmarklet/index.html from src/reader.js.
// Run: node build.js
//
// One source of truth (src/reader.js) means the extension and the bookmarklet
// can never drift. Edit the reader, run this, commit all three.

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const readerPath = path.join(ROOT, 'src', 'reader.js');
const bgPath = path.join(ROOT, 'extension', 'background.js');
const htmlPath = path.join(ROOT, 'bookmarklet', 'index.html');

const reader = fs.readFileSync(readerPath, 'utf8');

// --- Light, safe minifier for the bookmarklet ---------------------------------
// Only strips comments and trims/joins lines. Relies on the authoring rules in
// reader.js (semicolons everywhere, single-line template literals, no inline
// comments, no double quotes) so it never has to parse expressions.
function minify(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, '')        // block comments
    .split('\n')
    .map(l => l.trim())
    .filter(l => l && !l.startsWith('//'))   // full-line // comments + blanks
    .join('\n');
}

// === Extension =================================================================
// background.js = service-worker header (icon + listeners + storage load) followed
// by the reader function verbatim, so executeScript can serialize it by reference.
const bgHeader = `// GENERATED by build.js from src/reader.js — do not edit by hand.

// Generate toolbar icon: 3 white columns on dark background
function setIcon() {
  try {
    const s = 128;
    const canvas = new OffscreenCanvas(s, s);
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = '#1a1a1a';
    ctx.fillRect(0, 0, s, s);
    ctx.fillStyle = '#fdf9f3';
    const colW = 18, colH = 80, top = 24, gap = 14;
    const totalW = 3 * colW + 2 * gap;
    const startX = (s - totalW) / 2;
    for (let i = 0; i < 3; i++) {
      ctx.fillRect(startX + i * (colW + gap), top, colW, colH);
    }
    chrome.action.setIcon({ imageData: ctx.getImageData(0, 0, s, s) });
  } catch (e) {}
}

chrome.runtime.onInstalled.addListener(setIcon);
chrome.runtime.onStartup.addListener(setIcon);

// Toolbar button click (shortcut via _execute_action fires this too).
// Load saved settings first, then inject the reader with them as an argument
// so there's no first-paint flash of default styling.
chrome.action.onClicked.addListener((tab) => {
  chrome.storage.local.get('_npcols', (data) => {
    chrome.scripting.executeScript({
      target: { tabId: tab.id },
      func: toggleNewspaperColumns,
      args: [data && data._npcols ? data._npcols : null, 'chrome'],
    });
  });
});

// ---------------------------------------------------------------------------
// Core reader — injected into the active tab
// ---------------------------------------------------------------------------
`;

fs.writeFileSync(bgPath, bgHeader + reader);

// === Bookmarklet ===============================================================
// Wrap the reader in an IIFE that calls it in 'local' (localStorage) mode, encode
// it as a JS string literal, and splice it into the CODE line of index.html.
const body = minify(reader) + "\ntoggleNewspaperColumns(null, 'local');";
const wrapped = 'javascript:(function(){' + body + '})();';

// JSON.stringify yields a valid, fully-escaped JS string literal. The extra
// </ -> <\/ pass guarantees the literal can't contain a </script> sequence that
// would prematurely close the <script> tag it lives in.
const literal = JSON.stringify(wrapped).split('</').join('<\\/');

let html = fs.readFileSync(htmlPath, 'utf8');
const marker = /const CODE = [\s\S]*?;\s*\/\* end-bookmarklet \*\//;
if (!marker.test(html)) {
  console.error('ERROR: could not find the CODE marker in bookmarklet/index.html');
  process.exit(1);
}
html = html.replace(marker, 'const CODE = ' + literal + '; /* end-bookmarklet */');
fs.writeFileSync(htmlPath, html);

console.log('Built:');
console.log('  extension/background.js   (' + (bgHeader + reader).length + ' bytes)');
console.log('  bookmarklet/index.html    (bookmarklet ' + wrapped.length + ' bytes)');
